### ISSUE TITLE
Invalid event detected by scratch of Bluetooth keyboard on Apple iPad

### ISSUE THREAD

**Issue by lihongtao2012** [LLK/scratch-www#3551] opened 2019-11-19 09:29 UTC
When I am using the Apple iPad to connect the Bluetooth keyboard, I do some event detection actions. I find that I cannot respond. As follows:

![FE8664106AC0F30A35CA50C4E83A7DF0](https://user-images.githubusercontent.com/7009005/69134522-8ea89e00-0af2-11ea-8ca0-af9d51eb4ba2.png)

![8E034FBB55BDB02A83A48B08006BA057](https://user-images.githubusercontent.com/7009005/69134012-d975e600-0af1-11ea-886a-b43dc8396429.png)

Safari on IOS 12 system

**Comment by apple502j** [comment] 2019-11-19 10:09
Duplicate of LLK/scratch-gui#4244

**Comment by lihongtao2012** [comment] 2019-11-19 11:18
@apple502j  I just downloaded his project. I did a real machine test. It's not easy to use

**Closed** 2019-11-21 02:18 UTC
