### ISSUE TITLE
Removing a curaotr multiple times

### ISSUE THREAD

**Issue by LankyBox01** [LLK/scratch-www#6008] opened 2021-08-30 18:29 UTC
If multiple people remove the same curator at the same time, it may result in... well... this
![image](https://user-images.githubusercontent.com/79767244/131386726-2788e087-aacb-4ea1-b555-171c2af46027.png)

This may also happen if you open 20 tabs and remove the curator from each tab. No error appears telling you that the curator was already removed.
This is because the api for removing curators (/site-api/users/curators-in/${studioId}/remove/?usernames=) doesn't perform a check if the curator is in the studio. Just removes it and adds an activity message.
I believe this is the same issue as #5986

**Comment by BryceLTaylor** [comment] 2021-09-02 21:02
closing as duplicate of #5986

**Closed by BryceLTaylor** 2021-09-02 21:02 UTC
