### ISSUE TITLE
Future Month Can be Chosen on Join Flow

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#4109] opened 2020-06-17 14:05 UTC
Future month can be chosen on Join Flow without encountering any error. Here is a screenshot-
<img width="398" alt="Future month" src="https://user-images.githubusercontent.com/61620631/84907997-b5a16f80-b0d5-11ea-9c48-49b02e2f7280.png">

### Steps to Reproduce

Complete all steps before the birth date step and choose a future month.

### Operating System and Browser

Windows 10 Pro, Firefox 77.0.1 (64-bit)

**Comment by Accio1** [comment] 2020-06-17 14:07
Duplicate of #3852

**Comment by R4356th** [comment] 2020-06-17 14:11
> 
> 
> Duplicate of #3852

Oops! Closing...

**Comment by R4356th** [comment] 2020-06-17 14:12
Wait, that is closed. Maybe this could be labelled "wontfix"? // cc @benjiwheeler, @BryceLTaylor

**Closed** 2020-06-17 19:53 UTC
