### ISSUE TITLE
Can't download Scratch device plugin

### ISSUE THREAD

**Issue by tjvr** [LLK/scratch-www#725] opened 2016-07-14 12:33 UTC
(Not sure whether to report this at [scratchx](https://github.com/llk/scratchx/issue) or here, but seeing as the `scratchr2` repo is private, this seems like as good a place as any...)

**<https://scratch.mit.edu/info/ext_download/> 404s**.

This is linked from the [ScratchX homepage](http://scratchx.org/).

**Comment by jwzimmer** [comment] 2016-07-14 13:52
Thank you for documenting this, @tjvr!

We are tracking this issue elsewhere already, so I'm going to close this case.

But until the issue is resolved, you can download the device plugin from the Tips Window:
- Go to the Editor ("Create" link on the homepage)
- Open the Tips window on the right-hand side
- Look under Blocks -> Extensions -> Extensions -> LEGO WeDo 1.0 or Picoboard Setup

<img width="334" alt="screen shot 2016-07-14 at 9 51 47 am" src="https://cloud.githubusercontent.com/assets/1320456/16841746/a014ba5c-49a8-11e6-8bea-dbe7c5bf1440.png">

Let me know if you have any difficulties with that! Thanks. : )

**Closed by jwzimmer** 2016-07-14 13:52 UTC

**Comment by tjvr** [comment] 2016-07-14 21:52
Thanks for the tip!
