### ISSUE TITLE
Flagged Comments' Author Unclickable

### ISSUE THREAD

**Issue by JoelGritter** [LLK/scratch-www#3026] opened 2019-06-04 12:10 UTC
https://scratch.mit.edu/projects/191450372/#comments-113209445

<img width="702" alt="Screen Shot 2019-06-04 at 08 07 02" src="https://user-images.githubusercontent.com/13542746/58877815-c1272180-869f-11e9-8273-470032d0034b.png">

So in this comment, both `GulpTea*` and my user icon do not lead to my profile.

### Steps to Reproduce

The bug seems to happen when a comment flagged by the filter is directly linked to from the mod queue.

### Operating System and Browser

Mac OS 10.14.5 Chrome 74.0.3729.169

**Comment by colbygk** [comment] 2019-06-04 12:18
Note: when viewing the comment without linking directly to it, the avatar+username are clickable. Maybe a z-index issue with how the double highlighting is setup.

Not clickable:
https://scratch.mit.edu/projects/191450372/#comments-113209445
![ezgif-5-8e42d2695e63](https://user-images.githubusercontent.com/192393/58878284-e9635000-86a0-11e9-83fb-ec11ce9aeab0.gif)

Clickable:
https://scratch.mit.edu/projects/191450372/
![ezgif-5-8b997d3ba7d9](https://user-images.githubusercontent.com/192393/58878446-4959f680-86a1-11e9-8da9-816325a665f8.gif)

**Comment by towerofnix** [comment] 2019-06-04 13:03
Duplicate of #2647 I believe.

**Closed** 2019-06-04 13:40 UTC
Labels: bug
