### ISSUE TITLE
Clicking anywhere in the player prior to project start does not start project

### ISSUE THREAD

**Issue by KennethSweezy** [LLK/scratch-www#2641] opened 2019-01-09 03:38 UTC
While the green flag is placed in the center of the player (before the initial project start) it is required that you click the circle that the green flag is located within, this is different than the previous version of the Scratch website.

See the following GIF:
[ImgBB](https://ibb.co/JvHgbxq)

### Steps to Reproduce
1. Navigate to any project page
2. Try starting the project by clicking elsewhere (outside of the green flag circle) within the player
3. Notice it doesn't work like it used to

### Possible Solution
Start a project on click anywhere inside of the player

### Operating System and Browser
Mozilla/5.0 (X11; CrOS x86_64 11151.59.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.94 Safari/537.36

**Comment by apple502j** [comment] 2019-01-09 07:57
Duplicate of LLK/scratch-gui#4229

**Comment by benjiwheeler** [comment] 2019-01-09 13:11
Thanks, @KennethSweezy and @apple502j

**Closed by benjiwheeler** 2019-01-09 13:11 UTC
