### ISSUE TITLE
Automatic And Manual 

### ISSUE THREAD

**Issue by EndlessBlaze** [LLK/scratch-www#4126] opened 2020-06-20 14:09 UTC
As much as i love the idea of having custom thumbnails the only problem would be, if some people still wanted to use the Manuel thumbnail
I suggest that we keep a manual way to put a thumbnail and also have the automatic option

Maybe when you press share you can choose one of 2 options which are.......
1. Would you like to use an auto generated image from your project?
2. Would you like to upload a thumbnail for your project?

**Comment by apple502j** [comment] 2020-06-20 14:20
@EndlessBlaze Hi, please comment on #4092 instead of making a new issue!

**Comment by GrahamSH-LLK** [comment] 2020-06-21 14:24
@EndlessBlaze Please close this.

**Comment by BryceLTaylor** [comment] 2020-06-23 14:27
Closing as a duplicate of #4092

**Closed by BryceLTaylor** 2020-06-23 14:27 UTC
