### ISSUE TITLE
[Homepage] commas not showing in # of projects in Safari

### ISSUE THREAD

**Issue by ntlrsk** [LLK/scratch-www#356] opened 2016-02-06 18:51 UTC
Home page in Safari doesn't show commas in number of projects (when logged out).
Reproduced on two Mac laptop computers  - in Safari only (Mac OS X 10.10.5). 

![image](https://cloud.githubusercontent.com/assets/4721032/12868652/b7814392-ccd8-11e5-8ae2-4370f34f3cf0.png)

**Comment by TheGrits** [comment] 2016-02-06 22:32
Not happening to me. ChromeOS 7647.73.0, Chrome 48.0.2564.92, Flash 20.0 (release 0)

**Comment by technoboy10** [comment] 2016-02-06 23:04
Can also reproduce in Safari 9.0.3 on OS X 10.11.3.

**Comment by Jonathan50** [comment] 2016-02-06 23:37
Weird.
> Double-clicking the number on Safari brings up a FaceTime dialog - perhaps Safari is treating the string as a phone number?

Likely it.

**Comment by thisandagain** [comment] 2016-03-03 17:05
@technoboy10 I think that's exactly right. Good catch.

**Comment by mewtaylor** [comment] 2016-03-22 14:56
Turns out this is an issue with `toLocaleString`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString. It doesn't appear to have support in Safari.

This should be solved by moving to using react-intl for number formatting.

**Closed** 2016-03-22 16:14 UTC
Labels: has-patch, prio-medium
