### ISSUE TITLE
touching mouse pointer works, even when mouse and sprite are off stage

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-www#4124] opened 2020-06-19 23:38 UTC
Demo: https://scratch.mit.edu/projects/406347413/

Thanks to user https://scratch.mit.edu/users/TimMcCool/ for finding this (and sorry about our plan to remove it!)

**Comment by apple502j** [comment] 2020-06-20 00:45
Duplicate of LLK/scratch-gui#5243

**Comment by BryceLTaylor** [comment] 2020-06-23 14:31
Closing as duplicate

**Closed by BryceLTaylor** 2020-06-23 14:31 UTC
Labels: Low Impact, Low Severity, bug
