### ISSUE TITLE
If you remix, share, and go back to project page, the comments for the original project show up

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-www#4093] opened 2020-06-11 18:14 UTC
It's confusing because you think you're so famous for a second

### Steps to Reproduce
Remix famous project
Share
See project page

### Operating System and Browser
Mac Safari

**Comment by BoomerScratch** [comment] 2020-06-11 18:19
Duplicate of #2608

**Closed** 2020-06-11 18:20 UTC
