### ISSUE TITLE
Deployment consistently breaks cached pages

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#787] opened 2016-07-28 19:50 UTC
Mac OS, Chrome 51.0.2704.103 (64-bit)

After deployment, navigating to any page within `www` will consistently result in a fatal javascript exception which results in either a blank page being rendered or a blank page with just the primary navigation. Refreshing the page will resolve the issue.

## Repro
- Navigate to any page that has been ported over to `www`
- Deploy `www`
- Navigate to the same page again

## Expected
- Page loads

## Actual
- Fatal javascript exception is thrown which prevents the page for rendering

## Reference
```
common.bundle.js:1 Uncaught TypeError: Cannot read property 'call' of undefined
```

![image](https://cloud.githubusercontent.com/assets/747641/17227099/a99da556-54da-11e6-9671-10f73c338b64.png)

**Comment by thisandagain** [comment] 2016-08-15 21:21
@rschamp Any thoughts on this? Moving to September milestone.

**Comment by rschamp** [comment] 2016-08-15 21:42
This wasn't showing up for me in Codetree, I guess because it had multiple assignees? I didn't look at this closely enough to know the root cause yet.

I had suspected that there was a mismatch between a cached view bundle and a fresh common bundle, in which case I would want to use versioned bundle filenames so that it was impossible for a page to load two bundles that didn't match.  The fact that the error is emanating from the common bundle kind of discounts that, but using versioned filenames might be a good idea anyway.

**Comment by St19Galla** [comment] 2016-08-25 20:05
I can confirm that this still happens on Mac Safari after today's deploy.

**Comment by rschamp** [comment] 2016-09-09 19:39
Resolved in #910

**Comment by thisandagain** [comment] 2016-10-04 19:58
Looks like this is happening again after our latest deploy. Re-opening for investigation.

**Comment by rschamp** [comment] 2016-10-14 20:14
The `Cache-Control: no-cache` header has been set on all the files in S3.  This should cause browsers to actually observe the ETags.  We should keep an eye out, but this should be fixed for the next deploy.

**Closed by rschamp** 2016-10-14 20:14 UTC
Labels: prio-high
