### ISSUE TITLE
Remove CHROME_APP_AVAILABLE feature flag

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#3797] opened 2020-04-10 14:00 UTC
The `CHROME_APP_AVAILABLE` feature flag is no longer needed as the app has been released, and the flag id currently set to always return true. 

We should remove the flag and all the places that use it.

Note, the `feature-flag` library item should be kept for use with other feature flags in future.

**Comment by apple502j** [comment] 2020-04-10 14:48
Duplicate of #3548

**Closed** 2020-04-13 14:40 UTC
Labels: ergonomics, tech debt
