### ISSUE TITLE
When scratch is down, the page links to the offline editor for 2.0 for download.

### ISSUE THREAD

**Issue by Explosion-Scratch** [LLK/scratch-www#3832] opened 2020-04-27 17:56 UTC
This isn't a huge issue but still is an easy fix, it was suggested over in the suggestions forum so I though I might port it here as well. This could confuse new scratchers if they open up the 2.0 offline editor instead of 3.0 when scratch is down.

**Comment by benjiwheeler** [comment] 2020-04-27 18:17
We have this filed in scratchr2 (which is private, so also good to have it here)

https://github.com/LLK/scratchr2/issues/5613

**Comment by Explosion-Scratch** [comment] 2020-04-27 18:27
Okay thank you!

**Comment by GrahamSH-LLK** [comment] 2020-06-09 14:00
@benjiwheeler Isn't this a LLK/scratch-www problem? The code for the broken page is here: https://github.com/LLK/scratch-www/blob/develop/static/cdn/trouble.html

**Comment by apple502j** [comment] 2020-06-09 14:27
They still need to have clone of the download page on download.scratch.mit.edu @GrahamSH-LLK

**Comment by GrahamSH-LLK** [comment] 2020-06-18 11:58
Ok! Thanks!

**Comment by R4356th** [comment] 2020-06-19 18:08
@benjiwheeler, isn't it possible to link installation files (or store links) instead of download.scratch.mit.edu? That way, it would not be necessary to keep updating different files at different places.

**Comment by carljbowman** [comment] 2020-10-01 20:47
Thanks for bringing this to out attention. We are going to look into addressing this, but this is a duplicate of an issue that we are tracking in scratchr2 repro.

**Closed by carljbowman** 2020-10-01 20:47 UTC
Labels: High Severity, Medium Impact, priority 2
