### ISSUE TITLE
Long project title extends outside of What's Happening box

### ISSUE THREAD

**Issue by seotts** [LLK/scratch-www#4044] opened 2020-05-28 16:11 UTC
When a project title that is very long and has no whitespace appears in the "What's Happening" box, its title extends beyond the box:
![image](https://user-images.githubusercontent.com/4612592/83165343-61f5c480-a0db-11ea-896f-f84e5e3a54a3.png)
![image](https://user-images.githubusercontent.com/4612592/83165367-691cd280-a0db-11ea-9f12-d57842018975.png)

### Steps to Reproduce

- Create a project with a long title with no whitespace. Share it.
- Log into an account that follows the account that shared the project. 

### Operating System and Browser

_Mac OS 10.15.4 Chrome Version 81.0.4044.138_

**Comment by R4356th** [comment] 2020-05-28 16:29
Duplicate of #4023, I believe.

**Comment by BryceLTaylor** [comment] 2020-05-28 19:14
Closing as duplicate

**Closed** 2020-05-28 19:14 UTC
