### ISSUE TITLE
Anything that is a subpage of /messages returns 403 instead of 404?

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1560] opened 2017-09-20 08:13 UTC
For some reason, anything under `/messages` returns 403 instead of 404 - even "asdf":
![what](https://user-images.githubusercontent.com/28599280/30633542-9b086128-9e1e-11e7-9c4b-14bec0475801.png)
I don't know if this is a bug, but if it isn't, I guess this is a question: why does this happen?

**Comment by thisandagain** [comment] 2017-09-20 11:58
This has to do with how our routing between our "legacy" systems and the newer website (this repo) works.

**Comment by rschamp** [comment] 2018-08-14 13:50
Dupe of #1182

**Closed by rschamp** 2018-08-14 13:50 UTC
Labels: prio-low
