### ISSUE TITLE
Project Doesn't Save When \b is put in any text

### ISSUE THREAD

**Issue by DREWNOLT** [LLK/scratch-www#4695] opened 2020-11-26 01:27 UTC
_When \b is put in any input, such as the "say" block, the project fails to save._
![Screenshot 2020-11-25 at 5 24 08 PM](https://user-images.githubusercontent.com/63362464/100297355-562c7300-2f43-11eb-93f9-3d130c4c1243.png)

### Steps to Reproduce

_put \b in any possible input in the editor_

### Operating System and Browser

_Chrome OS, Chrome 86_

**Comment by apple502j** [comment] 2020-11-26 02:41
Duplicate of LLK/scratch-parser#56

**Comment by BryceLTaylor** [comment] 2020-12-03 16:33
Closing as duplicate

**Closed by BryceLTaylor** 2020-12-03 16:33 UTC
