### ISSUE TITLE
Missing space on "Projects curated by" row

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-www#984] opened 2016-10-26 12:11 UTC
![image](https://cloud.githubusercontent.com/assets/3766964/19725505/c32449e8-9b53-11e6-9f14-101cf4709594.png)

Highly visible...

**Comment by rschamp** [comment] 2016-10-26 13:25
Dupe of https://github.com/LLK/scratch-www/issues/965 (fixed for this release)

**Closed by rschamp** 2016-10-26 13:25 UTC

**Comment by coke11** [comment] 2016-11-14 23:00
@rschamp There were three issues about this...
