### ISSUE TITLE
Project page is too wide

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-www#3821] opened 2020-04-22 22:31 UTC
This page looks funny
https://scratch.mit.edu/projects/127577570/
<img width="1560" alt="Screen Shot 2020-04-22 at 18 30 32" src="https://user-images.githubusercontent.com/2855464/80040205-96b4a180-84c7-11ea-9e14-2ffe0b368c64.png">

### Steps to Reproduce
Go to page https://scratch.mit.edu/projects/127577570/

### Operating System and Browser
Mac osx chrome

**Comment by benjiwheeler** [comment] 2020-04-23 18:06
Duplicate of https://github.com/LLK/scratch-www/issues/2853

A fix is in review, but no sense of when the fix will go in: https://github.com/LLK/scratch-www/pull/2518

**Closed by benjiwheeler** 2020-04-23 18:06 UTC
