### ISSUE TITLE
Embed projects don't work

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1661] opened 2017-11-08 11:18 UTC
### Expected behavior
Embedding projects (`<iframe allowtransparency="true" width="485" height="402" src="https://scratch.mit.edu/projects/embed/178433850/?autostart=false" frameborder="0" allowfullscreen></iframe>`) should work
### Actual behavior
It says "oh no, you don't have flash":
![image](https://user-images.githubusercontent.com/28599280/32546167-1ed1a5c6-c4b9-11e7-8c95-b9754217d835.png)
### Steps to reproduce
1. Create a random HTML file with the content
```html
<iframe allowtransparency="true" width="485" height="402" src="https://scratch.mit.edu/projects/embed/178433850/?autostart=false" frameborder="0" allowfullscreen></iframe>
```
2. Open it with your browser.
3. See the iframe say "oh no, we're having trouble displaying this scratch project"
### Operating System and Browser
Windows 10, on Chrome and Firefox - I think it's not an OS issue though.

**Comment by colbygk** [comment] 2017-11-08 15:52
My suspicion is that this is related to Chrome and Firefox tightening their security model. I have reproduced this locally with Chrome 62.0.3202.89 (Official Build) (64-bit) on macOS 10.12.6. 

When looking at the Security pane from the dev tools for Chrome, I see:

![screen shot 2017-11-08 at 10 48 52 am](https://user-images.githubusercontent.com/192393/32558328-7ad4e3ac-c472-11e7-8a68-deebc490a513.png)

Normally all secure content must be loaded from a secure document. However Chrome does not print any console messages related to the attempted load of flash content. Adding `https://scratch.mit.edu:443` to the allow list under `Content Settings→Flash→Allow` makes no difference.

**Comment by kyleplo** [comment] 2017-12-29 18:16
Well, we won't have to worry about this in Scratch 3.0.

**Comment by amazinigmech2418** [comment] 2017-12-31 14:40
The strange thing is that it works on the embed website, but not in the iframe. It seems like the iframe is blocking the allowing of flash.

**Comment by amazinigmech2418** [comment] 2018-01-05 03:51
@Kenny2github I think the problem is that maybe, the files needed to load shockwave don't load correctly. Can you please give me the code for embedding projects so I could help?

**Comment by amazinigmech2418** [comment] 2018-01-05 03:56
The meta tag blocks iframe embeds. https://github.com/LLK/scratch-www/commit/f569d02e928d50d414bc3fe55b9fa7aedb8edfdf is the commit. @Kenny2github

**Comment by amazinigmech2418** [comment] 2018-01-05 04:06
https://github.com/LLK/scratch-www/issues/862 says that was fixed.

**Comment by amazinigmech2418** [comment] 2018-01-05 04:17
`  <script src="/js/<%= htmlWebpackPlugin.options.route.name %>.intl.js"></script>
    ` may have something to do with it since the /js directory doesn't exist based on this repo.

**Comment by amazinigmech2418** [comment] 2018-01-05 04:18
@colbygk Why would a source have a file protocol? It may have something to do with the code I found.

**Comment by amazinigmech2418** [comment] 2018-01-05 04:21
Wait. Never mind. The protocol was what was used to run the iframe. It used to work on everything though.

**Comment by apple502j** [comment] 2018-01-27 05:13
I'm going to use it for MediaWiki, so I can't neither change one's browser settings nor load another JS

**Comment by GreenBayRules** [comment] 2018-01-27 05:15
@Kenny2github So here's what I have found. It doesn't work when you load it (got the same error), but when you click on "Site settings" and click "Allow Flash" then it works for me.

**Comment by Kenny2github** [comment] 2018-01-27 05:21
@GreenBayRules this would look like a browser issue then - it doesn't show anything about the plugin being blocked, and it doesn't "ask" (which is my default). @colbygk opinions?

**Comment by GreenBayRules** [comment] 2018-01-27 05:27
You have to click on the i button.... here let me show you a gif @Kenny2github 

![kenny](https://user-images.githubusercontent.com/11379161/35468989-abcfc7be-02df-11e8-9639-f603ff14e552.gif)

**Comment by amazinigmech2418** [comment] 2018-01-27 18:30
Wow! That solution was way simpler than I thought...

**Comment by SheepTester** [comment] 2018-01-28 21:58
On Chrome, clicking on "this page" or the "get Adobe Flash player" button will make the browser prompt if you want to use Flash.

Whether or not Flash is enabled depends on the parent (so even if you have Flash enabled on Scratch, it won't run when embedded in a different domain with Flash disabled)

**Comment by amazinigmech2418** [comment] 2018-01-28 23:59
I made a Scratch extension that can allow Scratch web creators. I just created a website to embed one of my projects with it. Since it has a Scratch domain, the embedding works automatically.
```<!DOCTYPE html><html><head><title>Embed</title></head><body>      <iframe allowtransparency="true" width="485" height="402" src="//scratch.mit.edu/projects/embed/199839521/?autostart=false" frameborder="0" allowfullscreen></iframe></body></html>``` was the code for the website.

**Comment by colbygk** [comment] 2018-01-29 14:17
@amazinigmech2418 An extension for chrome?

**Comment by colbygk** [comment] 2018-01-29 14:26
@amazinigmech2418 Also, please provide the full version string of chrome that you are using.

**Comment by amazinigmech2418** [comment] 2018-01-29 23:51
@colbygk It's a Scratch extension that is run with a bookmarklet. It's also on ScratchX when you use the link in the ScratchX repo for it.

**Comment by amazinigmech2418** [comment] 2018-01-29 23:52
@colbygk What do you mean full string? If you mean the version of Chrome, how do you get it?

**Comment by colbygk** [comment] 2018-01-30 00:59
Type `about:` and enter for the url.

**Comment by amazinigmech2418** [comment] 2018-01-31 00:39
So would it be 63.0.3239.132? @colbygk

**Comment by kyleplo** [comment] 2018-01-31 12:00
@amazinigmech2418 I think this involves the different permissions the browser has.

**Comment by thisandagain** [comment] 2018-01-31 15:04
I think it's been established that this is due to the security model updates in Firefox and Chrome. Closing.

**Closed by thisandagain** 2018-01-31 15:04 UTC
Labels: bug
