### ISSUE TITLE
Teacher Registration - Cannot proceed past "Address" Step after one invalid attempt

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#645] opened 2016-06-30 19:43 UTC
![image](https://cloud.githubusercontent.com/assets/747641/16501766/0c8d8aae-3ed9-11e6-896a-33d3b653d6df.png)

#### Steps to Reproduce
- Complete form
- Press "Next Step"

#### Expected
- Either allow user to proceed or display error

#### Actual
- Registration does not advance and does not display an error
- No errors in JS console

**Comment by rschamp** [comment] 2016-06-30 19:48
I think this is a dupe of #608 — your zip code of 0 is making this an invalid address, but it's not telling you.

**Comment by thisandagain** [comment] 2016-06-30 19:55
I get the same result after changing it to a valid zipcode.

**Comment by rschamp** [comment] 2016-07-01 17:48
Fixed in #657

**Closed by rschamp** 2016-07-01 17:48 UTC
Labels: prio-high, staging, teacher accounts
