### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Chaos-emerald** [LLK/scratch-www#5396] opened 2021-05-13 12:29 UTC
No bug, but I want dark mode.

### Steps to Reproduce

None

### Operating System and Browser

Chrome OS and Chrome

**Comment by Emerald-chaos** [comment] 2021-05-13 12:30
@benjiwheeler or @BryceLTaylor Check this

**Comment by gosoccerboy5** [comment] 2021-05-13 15:30
This is already posted on the forums..

**Comment by Shluffy** [comment] 2021-05-13 16:01
> This is already posted on the forums..
> Also, looks like a duplicate on scratch-gui: [#59](https://github.com/LLK/scratch-gui/issues/59)

that seens ti be only the editor

**Comment by gosoccerboy5** [comment] 2021-05-13 16:03
> > This is already posted on the forums..
> > Also, looks like a duplicate on scratch-gui: [#59](https://github.com/LLK/scratch-gui/issues/59)
> 
> that seens ti be only the editor

I haven't contributed to Scratch, and am not active at all here, but I suspect it would be better to post there.

**Comment by jemunm378** [comment] 2021-05-14 10:15
Yeah, this been ask way to many times.

**Comment by BryceLTaylor** [comment] 2021-05-17 18:44
Duplicate of https://github.com/LLK/scratch-gui/issues/59

**Closed by BryceLTaylor** 2021-05-17 18:44 UTC
