### ISSUE TITLE
Remix of Project Has Comments from Remixed Project

### ISSUE THREAD

**Issue by GrahamSH-LLK** [LLK/scratch-www#4020] opened 2020-05-26 15:25 UTC
I created a remix of this project: https://scratch.mit.edu/projects/213522086
When I went to the project page of my remix, the comments from the remixed project were there. They stayed for about 2 reloads. 
### Steps to Reproduce

Go to a project
Open editor
Click Remix inside the editor.
Click on the button for the project page
See Comments
Reload
Comments Are gone
### Operating System and Browser

Chrome OS

**Comment by apple502j** [comment] 2020-05-26 15:54
Duplicate of #2608

**Closed** 2020-05-26 18:33 UTC
