### ISSUE TITLE
Translations broken in Chinese

### ISSUE THREAD

**Issue by kaschm** [LLK/scratch-www#381] opened 2016-03-10 18:48 UTC
Homepage doesn't translate in either simplified or traditional chinese (简体中文, 正體中文).

**Comment by TheGrits** [comment] 2016-03-10 19:31
I can reproduce this.
ChromeOS, Chrome 48

What's interesting is that the Scratch News title is changed to "news.scratchNews" with the link to the right of it becoming "general.viewAll".

**Comment by abee2** [comment] 2016-03-20 06:50
It is the same in Japanese.
My browser / operating system: Windows NT 10.0, Chrome 49.0.2623.87, Flash 21.0 (release 0)
![2016-03-20 15 32 45](https://cloud.githubusercontent.com/assets/972987/13903169/705935cc-eeb3-11e5-9f70-79f98f935487.png)

**Comment by ntlrsk** [comment] 2016-03-21 01:44
Picture of About page:
![image](https://cloud.githubusercontent.com/assets/4721032/13908950/ec7932bc-eee3-11e5-9c69-4459f7e2ba80.png)

**Comment by abee2** [comment] 2016-03-21 06:20
I confirmed this problem is fixed.
Thank you!

**Comment by ntlrsk** [comment] 2016-03-21 07:13
@abee2 Thank you for letting us know that you can see it's now fixed for Japanese.

**Comment by ntlrsk** [comment] 2016-03-21 11:25
Note:  "Japanese (Hiragana)" still to be fixed, as well as Simplified and Traditional Chinese.

**Comment by mewtaylor** [comment] 2016-03-21 11:58
Looks like yahoo changed its locale data about 15 days ago when `intl-messageformat` was built into version 1.3. I'm adding the languages that are affected to our `custom-languages.json` list now

**Comment by thisandagain** [comment] 2016-03-21 12:20
@mewtaylor Can you clarify where this update occurred? I don't remember seeing a commit updating `intl-messageformat`.

**Comment by mewtaylor** [comment] 2016-03-21 12:29
Whoops sorry thanks @thisandagain – https://github.com/yahoo/intl-messageformat/commit/6566e19892b2972f94e7e6cf637f8378f52387d4

**Comment by mewtaylor** [comment] 2016-03-21 12:47
@thisandagain pointed out that the upgrade to 1.3 upstream probably did not cause this issue, as we use a static version of react-intl in production. Thanks for that @thisandagain !

**Closed** 2016-03-21 12:48 UTC
Labels: prio-high
