### ISSUE TITLE
Console warning appears incorrectly on Edge and IE

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#1959] opened 2018-07-10 14:47 UTC
The new console warning should contain the word `STOP!` in red.  On Edge and IE it shows up without being red and it contains the formatting in plain text

Edge:
![consolewarningedge](https://user-images.githubusercontent.com/1088291/42517624-27553782-842e-11e8-8426-46f47db24e94.png)

IE:
![consolewarningie](https://user-images.githubusercontent.com/1088291/42517634-2d3352d8-842e-11e8-8f43-0d138da622ae.png)

### Steps to Reproduce

Open the console on Edge or IE
Note that the warning is not formatted correctly and the formatting info is printed

### Operating System and Browser

Edge on Windows
IE on Windows

This is from this pr: https://github.com/LLK/scratch-www/pull/1946

**Comment by JoelGritter** [comment] 2018-07-10 14:48
I'll look into this, since I made the PR in the first place.

**Comment by JoelGritter** [comment] 2018-07-10 14:54
According to the MDN docs, inline styling of console.log outputs is not supported in Internet Explorer, but should be supported in Edge: https://developer.mozilla.org/en-US/docs/Web/API/Console/log#Browser_compatibility

That explains why IE is not working. I'll need to do some more digging to figure out why Edge isn't cooperative.

**Comment by JoelGritter** [comment] 2018-07-10 15:00
Looks like it may be caused by my use of the -webkit-text-stroke, seeing as it isn't supported in Edge. I'll look into a suitable substitute, or another CSS rule that will emulate it. (Probably going to use some sort of `text-shadow` styling)

**Comment by joker314** [comment] 2018-07-10 17:21
For IE, I suggest you use `console.warn` or `console.error` just after a call to `console.clear` to attract similar attention. In addition, you could use capital letters or ASCII art (the latter might not work so well on screen readers -- not sure though) for the "STOP" text, to ensure it is definitely read

**Comment by Narulacodes** [comment] 2018-07-10 19:38
no warning on chrome.

**Comment by JoelGritter** [comment] 2018-07-10 19:41
@Narulacodes You're likely trying to find it on the site, but the changes haven't been pushed to the master branch yet, see #1952

**Comment by Narulacodes** [comment] 2018-07-10 19:41
@joker314  Yeah 

js`console.warn`, looks good and would be a good idea for Ie.
Thanks @JoelGritter

**Comment by JoelGritter** [comment] 2018-08-26 03:26
I hope to make a PR related to this issue on Monday.

**Comment by JoelGritter** [comment] 2018-08-27 23:54
Make that tomorrow

**Comment by JoelGritter** [comment] 2018-08-28 20:16
@thisandagain Do we want both IE and Edge to be supported for this, or just Edge?

**Comment by JoelGritter** [comment] 2018-08-28 20:35
I'm not sure what's going on, according to the MDN docs Edge is supposed to allow console.log() substitution strings: https://developer.mozilla.org/en-US/docs/Web/API/Console/log

I'll have to dig deeper into the issue.

**Comment by JoelGritter** [comment] 2020-03-10 15:25
@thisandagain Closing this issue, since all supported browsers are properly displaying the warning now: (Tested on MacOS)

Chrome:
<img width="1440" alt="Screen Shot 2020-03-10 at 11 19 11" src="https://user-images.githubusercontent.com/13542746/76328241-73d88000-62c1-11ea-9a3d-2b7f0c7cadb4.png">

Edge:
<img width="1440" alt="Screen Shot 2020-03-10 at 11 18 35" src="https://user-images.githubusercontent.com/13542746/76328283-82bf3280-62c1-11ea-915f-c4a1f636a522.png">

Firefox:
<img width="1440" alt="Screen Shot 2020-03-10 at 11 19 41" src="https://user-images.githubusercontent.com/13542746/76328351-92d71200-62c1-11ea-837e-34a0071f6247.png">

Safari:
<img width="1440" alt="Screen Shot 2020-03-10 at 11 20 13" src="https://user-images.githubusercontent.com/13542746/76328427-aaae9600-62c1-11ea-9bc4-4f15ca60daa2.png">

**Closed by JoelGritter** 2020-03-10 15:25 UTC
Labels: bug, edge
