### ISSUE TITLE
Error at end of Teacher Registration

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#696] opened 2016-07-07 16:20 UTC
I think ideally a user should never get this page at the end of registration:
<img width="666" alt="screen shot 2016-07-07 at 12 17 58 pm" src="https://cloud.githubusercontent.com/assets/1320456/16660602/12b35c92-443d-11e6-8aa2-8af16ce7c1e8.png">

If this is caused by a missing required field, the user should be notified of that before being able to proceed to the next step.

(It may have been caused by my not entering a phone number, but I'm not sure: https://github.com/LLK/scratch-www/issues/693)

**Comment by mewtaylor** [comment] 2016-07-07 17:22
@jwzimmer +1 – if I recall correctly, the original design also specified what you have suggested above. Your diagnosis that this is the cause of #693 seems right to me!

**Comment by jwzimmer** [comment] 2016-07-07 17:25
Tracking in #693.

**Comment by jwzimmer** [comment] 2016-07-27 23:45
Just got this again in Safari on staging, I am not sure how (I think possibly b/c I did not specify a state for American Samoa)?
<img width="711" alt="screen shot 2016-07-27 at 7 42 14 pm" src="https://cloud.githubusercontent.com/assets/1320456/17196413/85f14c50-5432-11e6-948c-698267d7b5b9.png">

I'm reopening this issue instead of https://github.com/LLK/scratch-www/issues/707 since that one specifies on production, and this is staging.

**Comment by jwzimmer** [comment] 2016-07-27 23:48
Just got it again after clearing all history in Safari... I think it may be if you choose a country that requires a state, then choose a state, then switch to a country that doesn't require a state?
<img width="720" alt="screen shot 2016-07-27 at 7 47 14 pm" src="https://cloud.githubusercontent.com/assets/1320456/17196496/0f517736-5433-11e6-9ca5-fd052f1d2111.png">

**Comment by jwzimmer** [comment] 2016-07-27 23:51
Got it again! I think I have repro steps now:
- Fill everything out as normal
- When you get to address, choose a country that requires states
- choose a state
- Switch country to one that doesn't require states, e.g. american samoa
- finish filling out step
- click next
- continue as usual
- see error at end
<img width="706" alt="screen shot 2016-07-27 at 7 49 27 pm" src="https://cloud.githubusercontent.com/assets/1320456/17196536/78551670-5433-11e6-8a03-e12dbb6a3fcd.png">

**Comment by jwzimmer** [comment] 2016-07-27 23:53
Actually, you might get this every time you choose a country that doesn't require a state?

**Comment by jwzimmer** [comment] 2016-07-27 23:56
Repro'd with these steps:
- Fill everything out as normal
- Switch country to one that doesn't require states, e.g. american samoa
- finish filling out step
- click next
- continue as usual
- see error at end

**Comment by rschamp** [comment] 2016-07-28 14:08
Fixed in LLK/scratchr2#3898

**Closed by rschamp** 2016-07-28 14:08 UTC
Labels: blocker, prio-high, teacher accounts
