### ISSUE TITLE
Spacing Mistake on FPC Row of Homepage

### ISSUE THREAD

**Issue by christanbalch** [LLK/scratch-www#987] opened 2016-10-27 13:05 UTC
The title of the Front Page Curator row on the homepage has a spacing mistake. Where it says "Projects Curated by [username]" there is not space between the "By" and the username. See image below:

![image](https://cloud.githubusercontent.com/assets/11506947/19767997/7f84b1a2-9c23-11e6-9cba-3c23b2d38b61.png)

**Comment by rschamp** [comment] 2016-10-27 13:05
Dupe of #965 (fixed for this release)

**Closed by rschamp** 2016-10-27 13:05 UTC

**Comment by coke11** [comment] 2016-11-14 22:59
lol I was going to create an issue for this when it was a problem
