### ISSUE TITLE
Credits page has duplicate names

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-www#1847] opened 2018-04-04 09:18 UTC
In the Acknowledgements section:
>...Han Xu, and the many volunteer Scratch Translators from around the world.
>...Han Xu.  With the help of Scratch Translators around the world, Scratch is available in many languages.

In the Previous Scratch Team Members section:
>...Amos Blanton... Oren Zuckerman, Gaia Carini...
>...Andrea Saxman, and Randy Jou.  Ben Berg, Amos Blanton...
>...Gaia Carini...
>...Oren Zuckerman

Basically, if you have ever contributed to Scratch's development your name is likely on the credits page twice by accident.

### Steps to Reproduce

Navigate to https://scratch.mit.edu/info/credits

### Operating System and Browser

Irrelevant

**Comment by GreenBayRules** [comment] 2018-04-04 14:42
I'm not able to reproduce this.

![image](https://user-images.githubusercontent.com/11379161/38314608-78db76b0-37db-11e8-9d48-186bc3b9914e.png)
![image](https://user-images.githubusercontent.com/11379161/38314632-88f681de-37db-11e8-8033-854391bf8a82.png)
![image](https://user-images.githubusercontent.com/11379161/38314637-8d17606c-37db-11e8-95fb-e2e098f5b1db.png)
![image](https://user-images.githubusercontent.com/11379161/38314672-a1dd982c-37db-11e8-9e95-675a38c7f2f8.png)
![image](https://user-images.githubusercontent.com/11379161/38314694-aaf57c90-37db-11e8-94e4-02fda496bbac.png)

**Comment by Kenny2github** [comment] 2018-04-04 14:58
Strange, I can:
![image](https://user-images.githubusercontent.com/28599280/38315629-710e7cc2-385b-11e8-8319-ae1046e039b0.png)
![image](https://user-images.githubusercontent.com/28599280/38315658-8042d67a-385b-11e8-895c-3079347a9736.png)
![image](https://user-images.githubusercontent.com/28599280/38315680-8c6eda34-385b-11e8-87c7-2df8cef902d3.png)
I guess I'll leave my OS and browser: Chrome 65.0.3325.181, Windows 8.1

**Comment by Kenny2github** [comment] 2018-04-04 14:59
OH I KNOW WHAT IT IS
Recently there was a pull that got merged to reduce translation work, putting all the names outside of l10n; but Edible Scratch (and probably Meow) never got that update. This is an Edible Scratch problem.

**Comment by ktrvs** [comment] 2018-04-04 16:54
@Kenny2github Oh yeah, I can repro this with Edible Scratch. Good catch!

**Comment by chrisgarrity** [comment] 2018-04-04 18:13
Closing this and tracking in the translations repo: https://github.com/LLK/scratchr2_translations/issues/13

**Closed by chrisgarrity** 2018-04-04 18:13 UTC
Labels: localization
