### ISSUE TITLE
Student Sign-up - Default country is `teacherRegistration.selectCountry`

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-www#785] opened 2016-07-28 16:34 UTC
Mac OS, Firefox 45.2.0

## Repro
- Create student
- Login as student
- Click "Next Step" button

## Expected
- Country drop-down to default to "select country"

## Actual
![image](https://cloud.githubusercontent.com/assets/747641/17220957/a13d2898-54bf-11e6-8ae8-c46dad6de901.png)

## Reference
![image](https://cloud.githubusercontent.com/assets/747641/17220926/790b0480-54bf-11e6-9644-6d9af884f477.png)

**Comment by mewtaylor** [comment] 2016-07-28 16:35
duplicate of #783

**Closed by mewtaylor** 2016-07-28 16:35 UTC
Labels: prio-high, staging, teacher accounts
