### ISSUE TITLE
[Translation] Homepage Intro Sprite text gets cut off in other languages, [German], [French]

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-www#1840] opened 2018-03-27 21:36 UTC
Expected Behavior:
In German and French the buttons in the Intro at the top of the signed out homepage should have text that all appears.  In English they say Try It Out, See Examples, and Join Scratch.

Actual Behavior:
In German, the text for the third button should say "Mach Mit Bei Scratch" but it gets cut off and actually says "Mach Mit Bei Sc" 
In French, the text of the second button should say "Voir Des Exemples" but it gets cut off and says "Voir Des Exemp".  The text of the 3rd button should say "Rejoins Scratch" but actually says "Rejoins Scratc"

Reproduction Test:
Navigate to the home page while signed out
Change the language to German
Look at the top of the page
Note, text that's too long
Change the language to French
Note the text is too long and is cut off.

I haven't checked the other languages yet

**Comment by JoelGritter** [comment] 2018-03-27 22:35
See also #1198

**Comment by Kenny2github** [comment] 2018-03-28 04:00
Yeah, this looks like it's a duplicate of #1198

**Comment by thisandagain** [comment] 2018-03-28 12:54
Tracking in #1198

**Closed** 2018-03-28 12:55 UTC
Labels: bug
