### ISSUE TITLE
load more button scrolls the page down

### ISSUE THREAD

**Issue by JeffaloBob** [LLK/scratch-www#4260] opened 2020-08-03 06:37 UTC
when pressing the load more button, the page is unexpectedly scrolled down.
![JiW7j8O6Jj](https://user-images.githubusercontent.com/40470736/89152983-4fc55600-d564-11ea-9ae1-e0e051b5e648.gif)
this seems to happen everywhere with a load more button
### Steps to Reproduce
1. find a place with a load more button. (eg explore)
2. press
3. you are scrolled down

### Operating System and Browser
Windows 10 1909 Chrome 84.0.4147.105

i don't know if this is a feature but it doesn't seem like its the expected outcome of the load more button.

**Comment by Accio1** [comment] 2020-08-04 19:58
I can reproduce on the same browser and OS. This only started happening recently (maybe the past 2 weeks?). Before that, the load more button would load the comments but wouldn't scroll down the page automatically.

**Comment by apple502j** [comment] 2020-08-05 01:21
This is probably Chrome bug; cannot repro on Firefox 79

**Comment by R4356th** [comment] 2020-08-05 09:57
Cannot repro on older versions of Chrome. I agree with @apple502j, this does look like a Chrome bug. But having said that, Scratch should try to fix this.

**Comment by mxmou** [comment] 2020-08-08 18:49
This can be fixed by setting `overflow-anchor: none`. I made [a userstyle](https://github.com/mxmou/customize-scratch/blob/master/loadmore.user.css) that fixes it.

**Comment by mxmou** [comment] 2020-08-08 18:50
It *is* a recent update to Chrome but I believe it's intentional.

**Comment by mxmou** [comment] 2020-08-10 09:16
@benjiwheeler Can you make this help wanted?

**Comment by Nambaseking01** [comment] 2020-08-11 11:26
This happens very often with me and I use Chrome all the time, so I'm pretty sure this isn't a Scratch issue in general. This bug is very annoying because I enjoy reading comments on famous projects and famous user's profiles to find inappropriate ones and just see all of the memes and compliment, and half of the time I can't read anything properly since this gets in my way. It would be helpful if this gets fixed soon.

**Comment by Nambaseking01** [comment] 2020-08-12 14:37
Just for more evidence, I just had this issue on the latest featured project - Scratch Farming Simulator 2.0.

**Comment by Nambaseking01** [comment] 2020-08-12 14:39
@mxmou Is there any way you can make a pull request with your userscript so it can get fixed easily? I don't think I'll be using that userscript on Tampermonkey until I'm sure this won't get implemented any time soon.

**Comment by Accio1** [comment] 2020-08-12 14:41
> @mxmou Is there any way you can make a pull request with your userscript so it can get fixed easily? I don't think I'll be using that userscript on Tampermonkey until I'm sure this won't get implemented any time soon.

@Nambaseking01 issues should be marked with help wanted before pull requests are submitted.

**Comment by mxmou** [comment] 2020-08-12 14:41
@Nambaseking01 I could make a PR but as @Accio1 said this isn't marked help wanted.

**Comment by Nambaseking01** [comment] 2020-08-12 14:42
@Accio1 @mxmou Ah OK, thanks for the confirmation. I'm new to this repository, I've only recently been posting on issues here and searching for bugs on the websites.

**Comment by benjiwheeler** [comment] 2020-10-01 17:19
@mxmou I'm going to check this with the design team to confirm that we want to change this -- if so, I'll mark it help wanted.

**Comment by benjiwheeler** [comment] 2020-10-01 17:27
@mxmou Yes, we would like the fix! Please do submit your PR when you get the chance, and please @ me.

**Comment by carljbowman** [comment] 2020-10-01 21:31
I believe everyone is on the same page, but just to confirm the design behavior: 

The current behavior is not desired: jumping to the end of the newly loaded comments after clicking the "Load More".

Instead, after clicking the "Load More" button, the comments should load but the scroll position should remain unaffected. Assuming the comment viewer does not scroll the page while comments are loading, this will result in same scroll position being the same as when the "Load More" button was clicked. This behavior ensures the comment viewer maintains their position in comments. The viewer can scroll down reading the newly loaded comments and click "Load More" again to load another batch of comments with the same behavior.

**Closed** 2020-10-15 18:04 UTC
Labels: High Impact, Low Severity, help wanted, needs discussion, priority 3
