### ISSUE TITLE
Add To Studio button does not appear in studio activity

### ISSUE THREAD

**Issue by leahcimto** [LLK/scratch-www#5065] opened 2021-02-27 17:39 UTC
(sorry for the confusing title)

_Describe the problem._
When a user adds a project to a studio with the "Add to Studio" button on the project page, the project will be added to the studio but in the studio activity log, it won't say anything.

### Steps to Reproduce

1. Make a project and share it
2. Using the add to studio button, add it to a studio you see on the list.
3. Now, go to whatever studio you added the project to and look in the activity tab. Notice it does not say you added the project to the studio, even though the project is in the studio.

### Operating System and Browser

macOS Big Sur 11.2, Chrome 88

**Comment by BryceLTaylor** [comment] 2021-03-04 22:01
This is referring to the "add to studio" button and modal on a project page.

**Comment by benjiwheeler** [comment] 2021-04-01 17:18
@leahcimto Thanks for filing this!

I think the problem is that the "Add to Studio" project page feature uses our newer, and less complete, scratch-api backend; whereas the My Stuff and Studio pages use the older, more complete scratchr2 backend. scratch-api doesn't do all of the related operations that scratchr2 does. But it should!

I'm renaming the issue a bit to reflect that.

**Comment by benjiwheeler** [comment] 2021-04-01 17:22
I'm closing this issue because it's entirely a backend problem, and we now have it filed there -- not because there's anything wrong with it! Thanks again, @leahcimto!

**Closed by benjiwheeler** 2021-04-01 17:22 UTC
Labels: High Severity, Medium Impact, bug, priority 3

**Comment by leahcimto** [comment] 2021-04-02 13:44
Alright! Thank you!
