### ISSUE TITLE
News page is missing

### ISSUE THREAD

**Issue by amylh** [LLK/scratch-www#4930] opened 2021-01-29 20:20 UTC
The News page is broken: https://scratch.mit.edu/news

### Steps to Reproduce
A screenshot of the current News page:
<img width="655" alt="image" src="https://user-images.githubusercontent.com/13766289/106323304-349e7f00-6245-11eb-8f0e-d5baca69d8a5.png">

### Operating System and Browser
macOS. Mozilla, Chrome

**Comment by BryceLTaylor** [comment] 2021-02-04 16:21
What are you expecting to see here?  How did you get to this page?

**Comment by amylh** [comment] 2021-02-04 16:27
> What are you expecting to see here? How did you get to this page?

To be honest, I'm not completely sure. Someone else brought this to my attention, claiming that this page used to display news related to Scratch.

**Comment by BryceLTaylor** [comment] 2021-02-04 21:47
duplicate of https://github.com/LLK/scratchr2/issues/5856

**Closed by BryceLTaylor** 2021-02-04 21:47 UTC
