### ISSUE TITLE
Website Often Fails to Load or Takes Too Long

### ISSUE THREAD

**Issue by R4356th** [LLK/scratch-www#3837] opened 2020-04-29 17:28 UTC
The Scratch website is often failing to load or taking too long for a few weeks.

### Steps to Reproduce

Go to any Scratch page.

### Operating System and Browser

My browser / operating system: Windows NT 10.0, Chrome 81.0.4044.129

**Comment by R4356th** [comment] 2020-04-29 17:29
One reason maybe the COVID-19 pandemic is causing too much traffic.

**Comment by benjiwheeler** [comment] 2020-04-30 19:06
Thanks, we are working on this, and are tracking it elsewhere. Since the cause isn't in this repo, i'm going to close it, but thanks for opening it, R4356th!

**Closed by benjiwheeler** 2020-04-30 19:06 UTC
