### ISSUE TITLE
Squished icons in Scratch News (Safari)

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#555] opened 2016-06-06 19:06 UTC
Safari Version 9.1 (11601.5.17.1)

Steps to repro: Log in to Scratch in Safari; Go to Homepage; Check out the icons in the Scratch News section.

Reported by: https://scratch.mit.edu/discuss/topic/200418/?page=1#post-2018413

<img width="974" alt="screen shot 2016-06-06 at 3 00 45 pm" src="https://cloud.githubusercontent.com/assets/1320456/15834150/feff8e62-2bf7-11e6-9a54-7d7c18bb4644.png">

**Comment by Choco31415** [comment] 2016-06-10 22:56
If it helps, I've already found a fix for the problem. Link: https://scratch.mit.edu/discuss/post/2019311/

Basically, the problem is that (it seems) Safari has a different implementation of flex compared to other browsers. Safari's flex implementation is causing images to be squished because the browser is trying to make more room for the text. Encapsulating each icon image with a <div style="flex-shrink:0"> fixes the issue.

**Comment by TheGrits** [comment] 2016-06-13 19:03
@Choco31415 Just tested the fix in Chrome 51, no negative effects here. I'll make a PR with the fix now.

**Comment by jwzimmer** [comment] 2016-06-15 15:00
I also encountered the squished icons in Chrome on my iPhone on staging:
![img_7633](https://cloud.githubusercontent.com/assets/1320456/16084879/51713f5a-32e8-11e6-8b03-735bdf438635.PNG)

**Comment by TheGrits** [comment] 2016-06-15 15:04
@jwzimmer #568 hasn't been merged yet, but it should prevent the squishing in all browsers.

**Comment by jwzimmer** [comment] 2016-06-15 15:33
@TheGrits Yes, I saw it hasn't been merged yet, just noting it also happened in Chrome since when I originally reported the issue I only mentioned Safari - mostly for my own good, so when I test it I'll know to test it in multiple browsers. : )

**Closed** 2016-06-16 15:17 UTC
Labels: prio-low
