### ISSUE TITLE
Major bugs accessing old comments

### ISSUE THREAD

**Issue by AmazingMech2418** [LLK/scratch-www#4525] opened 2020-10-16 00:00 UTC
This bug is really two problems. The first is that, in a profile with a lot of comments, if you scroll down far enough, it will stop scrolling and this message will appear: 
![image](https://user-images.githubusercontent.com/33498997/96197370-df519280-0f1f-11eb-9517-395727117dcf.png)
 The second is that, if you try to access page 68 of comments for any Scratcher, it fails and logs you out. If I try https://scratch.mit.edu/site-api/comments/user/griffpatch/?page=67 , it is fine, but if I try https://scratch.mit.edu/site-api/comments/user/griffpatch/?page=68 , it will log me out and show a 404 error. This being the 68th page is also consistent with Life_Tutor's profile on Scratch ( https://scratch.mit.edu/users/Life_Tutor ) with which I realized the issue. It will appear like this specifically:
![image](https://user-images.githubusercontent.com/33498997/96197496-44a58380-0f20-11eb-8733-c0fc6a202f81.png)
If you attempt to log back in from this page, it also fails.

### Steps to Reproduce

Bug 1:
1. Open a Scratch profile with a lot of comments (for example, griffpatch or Life_Tutor)
2. Open the JS console for observing the error.
3. Scroll down as far as you can (you can use a script to automatically scroll by pressing the "Load more" button on an interval)
4. Observe the error when it appears. 

Bug 2:
1. Open the API link for a Scratcher with a lot of profile comments at page 67.
2. Open it at page 68 and see that it fails on 68, but not 67.

### Operating System and Browser

Windows 10 on Chrome, although irrelevant since this is likely a server-side and client-side logic error or potentially an intended limit, although it restricts viewing old comments.

**Comment by AmazingMech2418** [comment] 2020-10-16 00:14
For bug 1, the issue is in scratchr2.

![image](https://user-images.githubusercontent.com/33498997/96198491-f9d93b00-0f22-11eb-832e-7d5d1316269e.png)


Bug 2 is likely in the backend code for the API endpoints.

**Comment by SausageMcSauce** [comment] 2020-10-16 13:41
> For bug 1, the issue is in scratchr2.

Please report scratchr2 bugs in the Bugs and Glitches forum only.

**Comment by BryceLTaylor** [comment] 2020-10-22 20:59
The 404 logging you out is a duplicate of https://github.com/LLK/scratchr2/issues/5389.  The javascript error is by design.

**Closed by BryceLTaylor** 2020-10-22 20:59 UTC

**Comment by AmazingMech2418** [comment] 2020-10-25 16:56
@BryceLTaylor How about the fact that you can only get to page 67 without a 404 error? Also, why is it by design? For example, griffpatch couldn't check messages from just 3 days ago because of the 40 page limit. It seems more like a bug to me...

**Comment by micahlt** [comment] 2021-04-13 03:10
@BryceLTaylor Yeah, what's the point in storing comments that are more than forty pages in if you won't allow them to be viewed?  Why is limiting pages to forty necessary or beneficial?

**Comment by jeffalo** [comment] 2021-04-13 06:19
@AmazingMech2418 it's probably by design because it takes a long time to load old comments (on the server) which could slow stuff down and rendering over 40 pages of comments on a web browser will also slow down a user's computer.

scratch-www comment pages (so far just the project page) do not have this issue because a comment id in a the url just shows that individual comment and it's replies

**Comment by AmazingMech2418** [comment] 2021-04-14 02:34
@jeffalo There could be a page system though like the forums...

And yeah, that is true.
