### ISSUE TITLE
If you remix a project from within the editor, the original project's comments will be visible

### ISSUE THREAD

**Issue by adroitwhiz** [LLK/scratch-www#3975] opened 2020-05-13 19:27 UTC
When you remix a project, the comments section on the remix's project page should be empty.
However, if you click the Remix button from inside the editor, the comments from the original project page will remain until you reload the page:
![Peek 2020-05-13 15-24](https://user-images.githubusercontent.com/25993062/81855979-19aca300-952e-11ea-9fe3-f7f49180c1ec.gif)

### Steps to Reproduce

1. While logged in, navigate to a project
2. Click "See inside"
3. Click the "Remix" button on the top bar of the project editor
4. Click the "See Project Page" button on the top bar of the project editor
5. Observe the comments that should not be there

### Operating System and Browser

All

**Comment by apple502j** [comment] 2020-05-14 04:00
Duplicate of #2608

**Closed** 2020-05-15 15:37 UTC
